apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-gitops-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alex-gitops-app
  template:
    metadata:
      labels:
        app: alex-gitops-app
    spec:
      containers:
        - name: web-server
          image: nginx:alpine
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: alex-gitops-app-service
  namespace: default
spec:
  selector:
    app: alex-gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
